export const CURSOR_DESIGN_MCP_SERVER_NAME = 'cursor-design' as const;

export const CURSOR_DESIGN_WORKSPACE_ROOT_ENV = 'CURSOR_DESIGN_WORKSPACE_ROOT' as const;

export const CURSOR_DESIGN_WORKSPACE_ROOTS_ENV = 'CURSOR_DESIGN_WORKSPACE_ROOTS' as const;
